# Generated by Django 5.1.5 on 2025-01-26 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissionfactor',
            old_name='activity_type',
            new_name='activity_name',
        ),
        migrations.RenameField(
            model_name='emissionfactor',
            old_name='factor',
            new_name='emission_factor',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_data',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='emission',
        ),
        migrations.RemoveField(
            model_name='emissionfactor',
            name='unit',
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='Default Activity Name', max_length=255),
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Amount of activity (e.g., km, kWh)')),
                ('calculated_emissions', models.FloatField(blank=True, help_text='Calculated emissions in kg CO2', null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.activity')),
                ('emission_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.emissionfactor')),
            ],
        ),
    ]
